# SPDX-FileCopyrightText: 2026 Robin Vobruba <hoijui.quaero@gmail.com>
#
# SPDX-License-Identifier: CC0-1.0

okhv = "2.4"
name = "Faire Maus - 3 Tasten"
repo = "https://codeberg.org/FairIT/assembly-kit/"
version = "0.1.0"
license = "CC-BY-SA-4.0"
licensor = "Nager IT e.V."
organization = "Nager IT e.V."
readme = "README.md"
image = "image/overview.jpg"
documentation-language = "de-DE"
#technology-readiness-level = "OTRL-5"
#documentation-readiness-level = "ODRL-4"
function = "One can tell at first glance what makes our mouse different from any other office mice since it has a wooden scroll wheel. But what really makes it unique is its sustainability: the mouse is being manufactured in a regional ‘Integrationswerkstatt’ (a repair and assembling shop that includes disabled people) in Regensburg under very fair conditions, meaning without involving any kind of exploitation or even child labour. When choosing our suppliers for the individual components, the social aspect is of particular importance for us. By publishing the entire supply chain on the internet, this is easily comprehensible for everyone."
#cpc-patent-class = "D03D 35/00"
#tsdc = "MEC"
#bom = "sBoM.csv"
manufacturing-instructions = "Bauanleitung_3_Tasten.md"
#user-manual = "Documentation/User_Guide/UserGuide.md"
#fabric-width-mm = 400

#[outer-dimensions]
#width = 400
#depth = 350
#height = 150
