
# SPDX-FileCopyrightText: 2023 Robin Vobruba <hoijui.quaero@gmail.com>
#
# SPDX-License-Identifier: Unlicense

name: movedo

on:
  push:
    branches: [ master, main, develop, markdown ]
    # Allows you to run this workflow manually from the Actions tab
    workflow_dispatch:
  release:
    types: [ published ]

# Sets permissions of the GITHUB_TOKEN to allow deployment to GitHub Pages
permissions:
  contents: read
  pages: write
  id-token: write

# Allow one concurrent deployment
concurrency:
  group: "pages"
  cancel-in-progress: true

jobs:
  build:
    name: Compile
    runs-on: ubuntu-latest
    container: hoijui/movedo:latest
    steps:
      - name: "Check out the repo"
        uses: actions/checkout@v4
        with:
          submodules: true
          # This makes sure we also get tags,
          # so we get the correct version; see bug:
          # https://github.com/actions/checkout/issues/701
          fetch-depth: 0

      - name: "Extract repos name"
        run: echo "REPO_NAME=${{ github.event.repository.name }}" >> $GITHUB_ENV

      - name: "Fix git repo rights"
        run: git config --global --add safe.directory "/__w/$REPO_NAME/$REPO_NAME"

      - name: Fix checkout ownership
        run: |
          # HACK Workaround for bug:
          # https://github.com/actions/runner/issues/2033
          mkdir -p /home/runner/work/_temp/_github_home
          printf "[safe]\n\tdirectory = /github/workspace" \
            > /home/runner/work/_temp/_github_home/.gitconfig

      - name: "tree - before build"
        run: |
          pwd
          tree

      - name: "DEBUGing - Check Xe*Tex availability"
        run: |
          which xetex || true
          which xelatex || true
          ls -la /usr/bin/xetex || true
          ls -la /usr/bin/xelatex || true
          echo "PATH=$PATH"

      - name: "Build with MoVeDo"
        run: |
          # HACK Latest version of pandoc should already be installed,
          #      but ... sometimes isn't.
          mvd print_pandoc_version
          mvd install_pandoc
          mvd print_pandoc_version
          mvd install_pdsite
          #tlmgr install latex latex-bin
          #tlmgr-sys --all
          fmtutil-sys --all
          export PATH="$PATH:$HOME/.pdsite/bin"
          export MVD_SINGLE_FILE=false
          mvd build
          # NOTE This is a HACK/FIX because ...
          # on some versions of the docker "magic"-universe,
          # this symlink is "fantastically" ... not present.
          ln -s /usr/bin/xetex /usr/bin/xelatex || true
          mvd make_pdf --mvd-individual --pdf-engine=xelatex
          #mvd make_pdf --mvd-individual --pdf-engine=/usr/bin/xetex

      - name: "tree - after build"
        run: |
          pwd
          tree

      - name: Upload artifact
        uses: actions/upload-pages-artifact@v3
        with:
          path: "build/"

  # Deployment job
  deploy:
    environment:
      name: github-pages
      url: ${{ steps.deployment.outputs.page_url }}
    runs-on: ubuntu-latest
    needs: build
    steps:
      - name: Deploy to GitHub Pages
        id: deployment
        uses: actions/deploy-pages@v4
